### ISSUE TITLE
Work Package wp-aa.csv

### ISSUE THREAD

**Issue by neilernst** [bhermann/DoR#18]

**Comment by anjiperera** [comment]
I would like to work on this please!

**Comment by aaleti** [comment]
Results of Phase 1
[wp-aa-results.csv](https://github.com/bhermann/DoR/files/6787964/wp-aa-results.csv)

**Comment by aaleti** [comment]
I completed this work package.

**Comment by anjiperera** [comment]
I completed this work package.

**Comment by aaleti** [comment]
I would like to work on this please!

**Comment by aaleti** [comment]
Results of Phase 2
[wp-aa-results.csv](https://github.com/bhermann/DoR/files/6788877/wp-aa-results.csv)

**Comment by aaleti** [comment]
I completed this work package.

**Comment by bhermann** [comment]
Thanks for you work on the package. I just included the data into the repository and it will appear on the website soon.
