### ISSUE TITLE
Work Package wp-ab.csv

### ISSUE THREAD

**Issue by neilernst** [bhermann/DoR#19]

**Comment by aaleti** [comment]
I would like to work on this please!

**Comment by aaleti** [comment]
Results of Phase 1. I spent approximately 30-45 minutes per paper
[wp-ab-results.csv](https://github.com/bhermann/DoR/files/6774174/wp-ab-results.csv)

**Comment by aaleti** [comment]
I completed this work package.

**Comment by anjiperera** [comment]
I would like to work on this please!

**Comment by aaleti** [comment]
Results of Phase 2
[wp-ab-results.csv](https://github.com/bhermann/DoR/files/6798277/wp-ab-results.csv)

**Comment by anjiperera** [comment]
I completed this work package.

**Comment by bhermann** [comment]
Thank you for your work. I just included this work package into the repository. The data should appear soon on the website.
