### ISSUE TITLE
Work Package wp-an.csv

### ISSUE THREAD

**Issue by neilernst** [bhermann/DoR#31]

**Comment by aaleti** [comment]
I would like to work on this please!

**Comment by aaleti** [comment]
Results of Phase 1. I spent 20-30 minutes per paper
[wp-an-results.csv](https://github.com/bhermann/DoR/files/6776460/wp-an-results.csv)

**Comment by aaleti** [comment]
I completed this work package.

**Comment by afonsohfontes** [comment]
I would like to work on this please!

**Comment by afonsohfontes** [comment]
I completed this work package.

[i31.csv](https://github.com/bhermann/DoR/files/6790406/i31.csv)

**Comment by bhermann** [comment]
Thanks for you work on the package. I just included the data into the repository and it will appear on the website soon.
