### ISSUE TITLE
Work Package wp-aw.csv

### ISSUE THREAD

**Issue by neilernst** [bhermann/DoR#40]

**Comment by karacitir** [comment]
I would like to work on this please!

**Comment by karacitir** [comment]
Results of Phase 1
[wp-aw-results.csv](https://github.com/bhermann/DoR/files/6810637/wp-aw-results.csv)

**Comment by karacitir** [comment]
I completed this work package.

**Comment by afonsohfontes** [comment]
I would like to work on this please!

**Comment by afonsohfontes** [comment]
I completed this work package.

[i40.csv](https://github.com/bhermann/DoR/files/6817194/i40.csv)

**Comment by bhermann** [comment]
Thank you for your work on this package. I included your data into the repository. It will appear on the website soon. 
I had to correct some 10.5555 DOIs and fixed a some spaces in DOIs here.
