### ISSUE TITLE
Work Package wp-be.csv

### ISSUE THREAD

**Issue by neilernst** [bhermann/DoR#48]

**Comment by XiaoLing941212** [comment]
I would like to work on this please!

**Comment by bhermann** [comment]
Hi @XiaoLing941212 . Is there an update on this work package?

**Comment by XiaoLing941212** [comment]
[wp-be-results.txt](https://github.com/bhermann/DoR/files/6792506/wp-be-results.txt)

Results for phase 1.

**Comment by XiaoLing941212** [comment]
I completed this work package.

**Comment by afonsohfontes** [comment]
I would like to work on this please!

**Comment by afonsohfontes** [comment]
I completed this work package.

[i48.csv](https://github.com/bhermann/DoR/files/6804036/i48.csv)

**Comment by bhermann** [comment]
@XiaoLing941212 Your file for phase 1 is using tabs for separators and currently cannot be processed. Could you recheck?

**Comment by XiaoLing941212** [comment]
@bhermann updated result for this package
[wp-be-results.csv.txt](https://github.com/bhermann/DoR/files/6826136/wp-be-results.csv.txt)

**Comment by bhermann** [comment]
@XiaoLing941212 You seem to have added a column called `sect_num` here. I will remove this column as it is not compatible with @afonsohfontes 's results. Please do not add columns or inform the next person of that fact so they don't produce an incompatible result.

**Comment by bhermann** [comment]
Thanks for your work on this package. I included it into the repository. It will appear soon on the website. 
I had only to correct some whitespaces in DOIs and Links. Watch out for those in the future. ;)
