### ISSUE TITLE
Work Package wp-bf.csv

### ISSUE THREAD

**Issue by neilernst** [bhermann/DoR#49]

**Comment by yrahul3910** [comment]
I would like to work on this please!

**Comment by yrahul3910** [comment]
I completed this work package.

[wp-bf.csv](https://github.com/bhermann/DoR/files/6722390/wp-bf.csv)

**Comment by afonsohfontes** [comment]
I would like to work on this please!

**Comment by afonsohfontes** [comment]
I completed this work package.

[i49.csv](https://github.com/bhermann/DoR/files/6775303/i49.csv)

**Comment by bhermann** [comment]
Great job @yrahul3910  and @afonsohfontes 
A couple of minor technical issues that I fixed during the inclusion to the website.
