### ISSUE TITLE
Work Package wp-bi.csv

### ISSUE THREAD

**Issue by neilernst** [bhermann/DoR#52]

**Comment by XueqiYang** [comment]
I would like to work on this!

**Comment by XueqiYang** [comment]
https://docs.google.com/spreadsheets/d/1wJ0AT6TH8Mohj7ejC0KeO8m0mmi8yL2by6O4evJqLZE/edit#gid=1587809933

**Comment by bhermann** [comment]
@XueqiYang : For reasons of automation, please attach the results as a CSV file, not as a Google spreadsheet. Thank you for your work! See: [Coding Guide](https://github.com/bhermann/DoR/blob/main/workflow/coding_guide.md)

**Comment by XueqiYang** [comment]
I completed this work package.

**Comment by XueqiYang** [comment]
Results of Phase 1
[wp-bi-results.csv](https://github.com/bhermann/DoR/files/6725387/wp-bi-results.csv)

**Comment by afonsohfontes** [comment]
I would like to work on this please!

**Comment by afonsohfontes** [comment]
I completed this work package.

[i52.csv](https://github.com/bhermann/DoR/files/6786206/i52.csv)

**Comment by bhermann** [comment]
Hi @XueqiYang and @afonsohfontes . Thanks for working on the work package. A few notes on this one:

- Please use the `paper_doi` and `reused_doi` column only for DOIs. IEEE Xplore and Zenodo Links will not work. I resolved all of these manually now. 
- You both record reuse of https://zenodo.org/record/3951724#.YNP8B2ZKgxk for this paper https://dl.acm.org/doi/10.1145/3368089.3409767 . I happen to be the author of that one and while it is true that we USE the dataset for the paper, it is actually the dataset created FOR the paper and thus not reuse. I took the liberty of removing those lines from your files. 

I corrected these and included this work package. Your work will soon appear on the website.

**Comment by bhermann** [comment]
Quick question for @XueqiYang and @afonsohfontes.
I noticed today, that your results files contain way more papers than was requested in the work package. 

Specifically, you report for the following DOIs:
10.1145/3368089.3409702 - wp-bm.csv #56
10.1145/3368089.3409703 - wp-bn.csv #57 
10.1145/3368089.3409725 - wp-bk.csv #54
10.1145/3368089.3409726 - wp-be.csv #48 
10.1145/3368089.3409727 - wp-bh.csv #51 
10.1145/3368089.3409685 - wp-bd.csv #47 
10.1145/3368089.3409686 - wp-bg.csv #50 
10.1145/3368089.3409682 - wp-bf.csv #49 
10.1145/3368089.3409683 - wp-bn.csv #57 

This is weird, because the file should only contain the results for wp-bi.csv. Could you please recheck how this came to be? As the history of this issue reveals some trouble with data conversion, I would ask you to critically review the process here.

**Comment by afonsohfontes** [comment]
I used his file as a starting point and merged my notes into it. I will build one from scratch and redo the process. Will post the updated version as soon as possible.

**Comment by bhermann** [comment]
Cool thanks @afonsohfontes . 
@XueqiYang Could you also have a look into this?

**Comment by afonsohfontes** [comment]
I am getting the same results for the first five papers in the package. And now I believe I understand what happened here. @bhermann 

He pasted the DOI into a line, then selected that line and dragged down it to fill the other empty lines for all entries in the of the same article.
Excel automatically increased the ending digit by one for each line, changing the original DOI.

I did my analysis, merged my result with his (I do that to check for any major differences), and also didn't check the last digit of the DOIs.

I will finish going through the files/articles correcting/double-checking everything.

I believe I can post the corrected versions of mine and his results soon.

**Comment by afonsohfontes** [comment]
Yes, my theory was correct. The same error repeated itself in the remaining articles.

Here are the corrected versions. @XueqiYang please double check if this matches your intentions.

[XueqiYang - corrected results.csv](https://github.com/bhermann/DoR/files/6823523/XueqiYang.-.corrected.results.csv)

[Afonso - corrected results.csv](https://github.com/bhermann/DoR/files/6823524/Afonso.-.corrected.results.csv)

**Comment by yrahul3910** [comment]
@afonsohfontes These seem to have spurious commas that lead to errors in parsing, could you please check that?

**Comment by afonsohfontes** [comment]
@yrahul3910 Sure, working on it.
I might not have checked the commas in the comments column.

I will get back to you asap.

**Comment by afonsohfontes** [comment]
[Afonso - corrected results.csv](https://github.com/bhermann/DoR/files/6825720/Afonso.-.corrected.results.csv)
[XueqiYang - corrected results.csv](https://github.com/bhermann/DoR/files/6825722/XueqiYang.-.corrected.results.csv)

**Comment by neilernst** [comment]
@bhermann @afonsohfontes I wonder if a parser would help here - check for proper comma use, verify valid DOI, etc

**Comment by yrahul3910** [comment]
@afonsohfontes Looks good--thanks!
@neilernst @bhermann @afonsohfontes Permission to delete the buggy comment? It's messing with our kappa score stats. The latest comment looks good to me.

**Comment by afonsohfontes** [comment]
@yrahul3910 I deleted all comments in these last versions I sent and kept the standard ';' separation my excel outputs. They should be ok. If there is anything buggy left, please go ahead and delete them.

**Comment by bhermann** [comment]
Thank you @afonsohfontes for fixing the files. I included them into the repository now. Quick note: the standard separation character we go for is `,` not `;`.
