### ISSUE TITLE
outsiders cannot assign themselves  to work packets. 

### ISSUE THREAD

**Issue by timm** [bhermann/DoR#61]

**Comment by bhermann** [comment]
Apparently GitHub doesn't support self-assignment of non-contributor. 
Idea for a quick fix: Tell people to comment on the issue that they want to be assigned and then we'll assign ourselves (or automate 😉)
What do you think?

**Comment by neilernst** [comment]
that makes sense ... shouldn't be too much trouble. 

also please merge the PR for the training set.

**Comment by bhermann** [comment]
I haven't found a matching GitHub action for this... Going to develop one over the weekend if I find the time.

**Comment by bhermann** [comment]
I would like to work on this please!

**Comment by bhermann** [comment]
Automatic assignment of issues working through GitHub Actions now. I'll adjust the documentation accordingly.

**Comment by bhermann** [comment]
All done.
