### ISSUE TITLE
Calculate R/R+ scores for DOR graph

### ISSUE THREAD

**Issue by neilernst** [bhermann/DoR#78]
in the paper we refer to this R/R+ score, referring to how often you reuse or are reused respectively. It would be great to show an example of this metric for our example graphs. 

The challenge as I see it is that the score is associated to an individual, and the graph nodes are papers. So the metric would have to aggregate all the Tim Menzies nodes into a Tim score. 

For the paper I don't think this has to be bulletproof or even to be honest automated. But it would be nice to show. 

We could also think of another metric like h-index, say \rho, that would represent the \rho papers with at least \rho instances of reuse.

**Comment by bhermann** [comment]
We already compute that on the website. Currently, this is a simple top 5 of the histogram for individuals and papers in the dataset. Should we change that to your definition of \rho?
![Screen Shot 2021-07-10 at 12 06 15](https://user-images.githubusercontent.com/1974799/125159376-564a4d80-e177-11eb-9609-49b23b767d15.png)

**Comment by neilernst** [comment]
doh! I guess I should look at our website!
