### ISSUE TITLE
statistics not being udpated

### ISSUE THREAD

**Issue by timm** [bhermann/DoR#79]
we can see ing the graph out-degrees of up to 7 but the RHS R+ numbers do not reflect that

so are the RHS nums connected currently to the graph?

**Comment by bhermann** [comment]
R+ is edges into a node. The thing being reused is the target of an edge. 
Edges out of a node indicate this node reusing things from the nodes it points to and that's the R number. 
The data for the RHS stats is coming from the same source as the graph, however, it is aggregated by researchers. So David Lo's current R+ of 9 means he has 9 papers that were reused by other people. 

As the graph the numbers currently only reflect reuse in the form of a published paper with a valid DOI. As the graph will represent other forms of reuse (arxiv, GitHub, etc.) the stats will also be updated. 

cf. `src/backend/RIndex.ts` and `src/tools/Histogram.ts`
